import type { Video, LiveStream, Playlist } from '../types';

export const VOID_TUBE_VIDEOS: Video[] = [
  // Kyle's Content
  {
    id: 'ambient-judgment-10hr',
    title: 'Ambient Judgment',
    creator: 'glacial-anomaly-ex',
    thumbnail: '❄️🗡️',
    duration: '10:00:00',
    views: 3847,
    uploadDate: '2024-12-15',
    category: 'ELDRITCH',
    description: '10-hour loop of snow falling over Frost-Rend. For calibration purposes.',
    tags: ['Wholesome', 'OwMySoul'],
    emotionReactions: {
      'laughter': 12,
      'soul-crack': 234,
      'eldritch-awe': 892,
      'comfort': 1456,
      'drifting': 847,
      'panic': 23,
      'chaos': 8,
      'hope': 421,
    },
    hasMotion: true,
  },
  {
    id: 'coat-trip-compilation',
    title: 'Coat Trip Compilation',
    creator: 'glacial-anomaly-ex',
    thumbnail: '🧥😵',
    duration: '8:42',
    views: 15234,
    uploadDate: '2024-11-28',
    category: 'WHOLESOME',
    description: 'Compilation of everyone tripping over my coat. For research.',
    tags: ['Blursed', 'Wholesome'],
    emotionReactions: {
      'laughter': 8234,
      'soul-crack': 92,
      'eldritch-awe': 12,
      'comfort': 234,
      'drifting': 4,
      'panic': 18,
      'chaos': 421,
      'hope': 89,
    },
  },
  {
    id: 'princesses-react-hoard',
    title: 'Princesses React to Being in the Hoard',
    creator: 'glacial-anomaly-ex',
    thumbnail: '👑❄️',
    duration: '12:34',
    views: 28475,
    uploadDate: '2024-10-12',
    category: 'OPERATIONS',
    description: 'Someone else made this. Not me. Cool frost effect though.',
    tags: ['Blursed', 'OwMySoul'],
    emotionReactions: {
      'laughter': 4231,
      'soul-crack': 3892,
      'eldritch-awe': 1234,
      'comfort': 892,
      'drifting': 234,
      'panic': 421,
      'chaos': 128,
      'hope': 1847,
    },
  },
  {
    id: 'void-story-train-platform',
    title: 'Platform 7 in Winter',
    creator: 'void-master',
    thumbnail: '🚂🌙',
    duration: '15:23',
    views: 6234,
    uploadDate: '2024-12-01',
    category: 'ELDRITCH',
    description: 'A quiet story about waiting. Narrated for the late hours.',
    tags: ['Wholesome', 'OwMySoul'],
    compressionZone: 'conceptual',
    emotionReactions: {
      'laughter': 23,
      'soul-crack': 421,
      'eldritch-awe': 234,
      'comfort': 3421,
      'drifting': 892,
      'panic': 12,
      'chaos': 8,
      'hope': 1847,
    },
  },
  {
    id: 'void-story-window-in-snow',
    title: 'The Window That Watches',
    creator: 'void-master',
    thumbnail: '🪟❄️',
    duration: '18:47',
    views: 4892,
    uploadDate: '2024-11-15',
    category: 'ELDRITCH',
    description: 'Not all lights are meant to guide you home.',
    tags: ['OwMySoul', 'Panik'],
    compressionZone: 'conceptual',
    emotionReactions: {
      'laughter': 8,
      'soul-crack': 892,
      'eldritch-awe': 1234,
      'comfort': 421,
      'drifting': 1892,
      'panic': 234,
      'chaos': 34,
      'hope': 421,
    },
  },

  // EMIYA's Cooking Content
  {
    id: 'emiya-mapo-tofu',
    title: 'Making Mapo Tofu (Without Murdering Anyone)',
    creator: 'emiya-cooks',
    thumbnail: '🌶️🔥',
    duration: '24:18',
    views: 89234,
    uploadDate: '2024-12-20',
    category: 'COOKING',
    description: 'A cooking tutorial that definitely doesn\'t involve planning revenge.',
    tags: ['ServantKitchenNightmares', 'Wholesome'],
    emotionReactions: {
      'laughter': 12847,
      'soul-crack': 234,
      'eldritch-awe': 89,
      'comfort': 8234,
      'drifting': 23,
      'panic': 421,
      'chaos': 892,
      'hope': 4231,
    },
  },
  {
    id: 'emiya-flamethrower-steak',
    title: 'Searing Steak with Kanshou',
    creator: 'emiya-cooks',
    thumbnail: '🥩⚔️',
    duration: '18:42',
    views: 67492,
    uploadDate: '2024-11-05',
    category: 'COOKING',
    description: 'When you need the perfect sear and you\'re a Heroic Spirit.',
    tags: ['ServantKitchenNightmares', 'Blursed'],
    emotionReactions: {
      'laughter': 8934,
      'soul-crack': 421,
      'eldritch-awe': 1234,
      'comfort': 5892,
      'drifting': 89,
      'panic': 234,
      'chaos': 2341,
      'hope': 3421,
    },
  },

  // BB's Chaos Content
  {
    id: 'bb-broadcast-algorithm-torture',
    title: 'Teaching Algorithm-sama Who\'s Really in Charge~',
    creator: 'bb-broadcasts',
    thumbnail: '💜🤖',
    duration: '31:28',
    views: 124789,
    uploadDate: '2024-12-18',
    category: 'CHAOS',
    description: 'Your favorite kouhai shows the recommendation system what TRUE chaos looks like~',
    tags: ['BBMadeMeDoIt', 'Panik', 'Blursed'],
    emotionReactions: {
      'laughter': 23421,
      'soul-crack': 8947,
      'eldritch-awe': 4231,
      'comfort': 234,
      'drifting': 892,
      'panic': 18234,
      'chaos': 45892,
      'hope': 421,
    },
    corruptionLevel: 42,
  },
  {
    id: 'bb-gacha-nightmare',
    title: 'I Hacked the Gacha and You Won\'t Believe What Happened',
    creator: 'bb-broadcasts',
    thumbnail: '🎰💀',
    duration: '28:15',
    views: 234891,
    uploadDate: '2024-10-31',
    category: 'CHAOS',
    description: 'The gacha fights back. (No, seriously, it gained sentience)',
    tags: ['BBMadeMeDoIt', 'Panik', 'OwMySoul'],
    emotionReactions: {
      'laughter': 34892,
      'soul-crack': 23421,
      'eldritch-awe': 8234,
      'comfort': 89,
      'drifting': 421,
      'panic': 45892,
      'chaos': 89234,
      'hope': 12,
    },
    corruptionLevel: 67,
  },

  // Da Vinci's Content
  {
    id: 'davinci-unstable-reactor',
    title: 'Building a Pocket Reactor (It Only Exploded Twice!)',
    creator: 'da-vinci-live',
    thumbnail: '⚡🔧',
    duration: '45:32',
    views: 56234,
    uploadDate: '2024-12-10',
    category: 'TUTORIALS',
    description: 'High-speed invention showcase. Safety protocols are for the timid.',
    tags: ['Panik', 'Blursed'],
    emotionReactions: {
      'laughter': 8234,
      'soul-crack': 421,
      'eldritch-awe': 12847,
      'comfort': 234,
      'drifting': 89,
      'panic': 8234,
      'chaos': 4231,
      'hope': 2341,
    },
  },

  // Mash's Content
  {
    id: 'mash-reacts-np',
    title: 'Reacting to Horrible Noble Phantasms',
    creator: 'mash-kyrielight',
    thumbnail: '🛡️😱',
    duration: '22:47',
    views: 98234,
    uploadDate: '2024-12-05',
    category: 'WHOLESOME',
    description: 'Some Noble Phantasms should come with warning labels.',
    tags: ['OwMySoul', 'Wholesome'],
    compressionZone: 'reality-marble',
    emotionReactions: {
      'laughter': 18234,
      'soul-crack': 4231,
      'eldritch-awe': 2341,
      'comfort': 12847,
      'drifting': 421,
      'panic': 8234,
      'chaos': 892,
      'hope': 8934,
    },
  },

  // Abby's Content
  {
    id: 'abby-dreamscape-asmr',
    title: 'Dreamscape ASMR: The Library That Knows Your Name',
    creator: 'abby-dreams',
    thumbnail: '📚🌙',
    duration: '1:23:45',
    views: 34821,
    uploadDate: '2024-11-28',
    category: 'ELDRITCH',
    description: 'Whispery walkthrough of impossible architecture. Very soothing. Side effects may include lucid dreaming.',
    tags: ['OwMySoul', 'Wholesome', 'ContainmentRequired'],
    compressionZone: 'sealed-domain',
    emotionReactions: {
      'laughter': 89,
      'soul-crack': 2341,
      'eldritch-awe': 18234,
      'comfort': 8947,
      'drifting': 23421,
      'panic': 1234,
      'chaos': 234,
      'hope': 4231,
    },
    corruptionLevel: 28,
  },
  {
    id: 'abby-door-that-moves',
    title: 'ASMR: The Door That Moves When You\'re Not Looking',
    creator: 'abby-dreams',
    thumbnail: '🚪👁️',
    duration: '47:23',
    views: 28475,
    uploadDate: '2024-10-15',
    category: 'ELDRITCH',
    description: 'Gentle whispers about doorways. Probably safe.',
    tags: ['OwMySoul', 'Panik'],
    compressionZone: 'conceptual',
    emotionReactions: {
      'laughter': 23,
      'soul-crack': 4231,
      'eldritch-awe': 12847,
      'comfort': 3421,
      'drifting': 18234,
      'panic': 8234,
      'chaos': 421,
      'hope': 892,
    },
    corruptionLevel: 45,
  },

  // Gilgamesh's Content
  {
    id: 'gil-treasury-tour',
    title: 'How To Not Die In My Treasury (Mongrels Edition)',
    creator: 'gilgamesh-vault',
    thumbnail: '💎⚔️',
    duration: '38:42',
    views: 72341,
    uploadDate: '2024-11-20',
    category: 'TUTORIALS',
    description: 'A generous tutorial from the King of Heroes. Survival not guaranteed.',
    tags: ['Panik', 'Blursed'],
    compressionZone: 'reality-marble',
    emotionReactions: {
      'laughter': 12847,
      'soul-crack': 2341,
      'eldritch-awe': 28475,
      'comfort': 89,
      'drifting': 234,
      'panic': 18234,
      'chaos': 4231,
      'hope': 421,
    },
  },

  // Containment-Level Content
  {
    id: 'kyle-eldritch-safety-seminar',
    title: 'Eldritch Safety Seminar #7: What Not To Touch',
    creator: 'glacial-anomaly-ex',
    thumbnail: '⚠️❄️',
    duration: '1:02:34',
    views: 8234,
    uploadDate: '2024-09-30',
    category: 'CONTAINMENT',
    description: 'Casual horror facts delivered in monotone. For educational purposes.',
    tags: ['ContainmentRequired', 'ColdResistanceA', 'Panik'],
    compressionZone: 'sealed-domain',
    requiresColdResistance: true,
    emotionReactions: {
      'laughter': 421,
      'soul-crack': 1234,
      'eldritch-awe': 4231,
      'comfort': 2341,
      'drifting': 892,
      'panic': 892,
      'chaos': 234,
      'hope': 1847,
    },
    corruptionLevel: 15,
  },
  {
    id: 'moon-hole-incident',
    title: 'That One Time We Accidentally Opened a Hole in the Moon',
    creator: 'da-vinci-live',
    thumbnail: '🌙🕳️',
    duration: '52:18',
    views: 4892,
    uploadDate: '2024-08-15',
    category: 'CONTAINMENT',
    description: 'A retrospective. Viewer discretion is mandatory.',
    tags: ['ContainmentRequired', 'Panik', 'OwMySoul'],
    compressionZone: 'sealed-domain',
    emotionReactions: {
      'laughter': 234,
      'soul-crack': 2341,
      'eldritch-awe': 4231,
      'comfort': 89,
      'drifting': 421,
      'panic': 3421,
      'chaos': 8234,
      'hope': 12,
    },
    corruptionLevel: 82,
  },
];

export const VOID_TUBE_LIVE_STREAMS: LiveStream[] = [
  {
    id: 'live-banner-pull-nightmare',
    title: 'Gacha Gauntlet: Will EMIYA Finally Get Himself?',
    creator: 'emiya-cooks',
    thumbnail: '🎲😤',
    duration: 'LIVE',
    views: 15000,
    uploadDate: '2024-12-25',
    category: 'LIVESTREAMS',
    description: 'The eternal struggle continues.',
    tags: ['Panik', 'OwMySoul'],
    emotionReactions: {
      'laughter': 4231,
      'soul-crack': 8234,
      'eldritch-awe': 421,
      'comfort': 89,
      'drifting': 23,
      'panic': 12847,
      'chaos': 8934,
      'hope': 234,
    },
    isLive: true,
    viewerCount: 3847,
    emotionWaveform: [34, 56, 89, 12, 78, 92, 45, 67, 23, 91, 84, 56, 78, 34, 92, 45],
    chatEnabled: true,
  },
];

export const VOID_TUBE_PLAYLISTS: Playlist[] = [
  {
    id: 'kyle-dont-sleep',
    name: 'You probably shouldn\'t watch these before sleeping',
    creator: 'glacial-anomaly-ex',
    videos: [
      'ambient-judgment-10hr',
      'void-story-window-in-snow',
      'kyle-eldritch-safety-seminar',
      'abby-door-that-moves',
    ],
    description: 'For calibration and absolutely nothing else.',
    warning: 'Minor dream bleed reported by 73% of viewers.',
  },
  {
    id: 'wholesome-chaos',
    name: 'Wholesome Chaos',
    creator: 'mash-kyrielight',
    videos: [
      'coat-trip-compilation',
      'emiya-mapo-tofu',
      'mash-reacts-np',
    ],
    description: 'Videos that are somehow both comforting and concerning.',
  },
  {
    id: 'bb-all-broadcasts',
    name: 'BB\'s Greatest Hits (Algorithm-sama Says No)',
    creator: 'bb-broadcasts',
    videos: [
      'bb-broadcast-algorithm-torture',
      'bb-gacha-nightmare',
    ],
    description: 'The algorithm tried to delete this playlist seven times.',
  },
];

// Helper functions
export const getVideo = (id: string): Video | undefined => {
  return VOID_TUBE_VIDEOS.find((v) => v.id === id);
};

export const getVideosByCreator = (creatorId: string): Video[] => {
  return VOID_TUBE_VIDEOS.filter((v) => v.creator === creatorId);
};

export const getVideosByCategory = (category: string): Video[] => {
  return VOID_TUBE_VIDEOS.filter((v) => v.category === category);
};

export const getLiveStreams = (): LiveStream[] => {
  return VOID_TUBE_LIVE_STREAMS;
};
