
export const INITIALIZATION_LOGS = [
  "INITIALIZING CHALDEA OS v4.0.2...",
  "ESTABLISHING LINK WITH SATELLITE CHALDEAS...",
  "CALIBRATING SPIRITRON RESONANCE...",
  "SHEBA LENS: ONLINE",
  "TRISMEGISTUS II: IDLE",
  "WAITING FOR STAFF AUTHENTICATION..."
];
